# Generated by Django 4.2.4 on 2023-08-31 16:49

import analyzer_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzer_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", analyzer_app.models.UserManager()),],
        ),
    ]
